### ISSUE TITLE
Change .desktop to log out

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#176]
We don't need the .desktop to launch the installer (since every install is treated like an OEM install and the installer is automatically launched in the session), but we should ship a .desktop that logs out for the Demo Mode

**Comment by cassidyjames** [comment]
@codygarver is this still applicable for how we plan to use the installer? I don't think it is for Pop!_OS, but I don't recall exactly how it's working in elementary OS.

**Comment by danrabbit** [comment]
Do we still need to do this now that the installer is a multi-process thing? I think installing from the demo user works now right?

**Comment by davidmhewitt** [comment]
It does, but whether we want it to?

On the positive side, being able to install in the demo mode works around a lot of the issues with screen resolution that you get in a VM, because you can open the display settings, change the resolution, then install.

On the downside, it's a lot easier to kill/interrupt/upset the installer by doing something else while it's installing.

**Comment by MrPotatoBobx** [comment]
maybe we can add a button to set screen resolution for vms in https://github.com/elementary/installer/pull/326

**Comment by danrabbit** [comment]
After some discussion, there are a few other odd things that happen if you run the installer during the session like it prompting you to try demo mode or select language and keyboard again etc. So it's easier to just logout. We can revisit the idea of running in session with other fixes later if that's really important
