### ISSUE TITLE
Add a screen to select Encryption options

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#213]
Distinst intends to support full-disk encryption so we need a screen to explain what that means and offer a choice of whether to do it or not

**Comment by cassidyjames** [comment]
![img_20180124_104939](https://user-images.githubusercontent.com/611168/35348179-83871934-00f4-11e8-9d9a-04452a58d56c.jpg)

**Comment by danrabbit** [comment]
We also need another screen after this for entering the encryption password. On this screen we'll want to explain that this is not the user's password, this is the computer's password

**Comment by cassidyjames** [comment]
We decided to go more secure-by-default and more heavily encourage encryption by making it the primary action. Since this is non-destructive at this point (users can go back until they choose their disk and start the installation), we don't need to totally protect them from clicking through to the next screen.

![encryption](https://user-images.githubusercontent.com/611168/35416957-7519e472-01e8-11e8-8a33-66c2fe9503d8.png)

The password screen acts as a sort of roadblock requiring user interaction, since they need to understand the implications of this password. They can still go back and opt out of encryption.

![encryption-password](https://user-images.githubusercontent.com/611168/35416960-7716b444-01e8-11e8-955f-17bd199a3d17.png)

**Comment by jackpot51** [comment]
That looks great!

**Comment by jackpot51** [comment]
@danrabbit how do you feel about the right side margins in the first image? The margins are smaller than in the second image

**Comment by danrabbit** [comment]
@jackpot51 Still ironing out all the details :)

**Comment by lewisgoddard** [comment]
This doesn't mention anywhere that it is _practically impossible for you to change this password_. I can see people using their normal password for this on a shared device and coming unstuck. I also feel like the "required each time you turn on" might get skimmed over because it's the third bullet point and maybe that should be bolded too.

**Comment by danrabbit** [comment]
@lewisgoddard We need to add UI to be able to change the password: https://github.com/elementary/switchboard-plug-security-privacy/issues/32

There is messaging there that this is not your user password.
