### ISSUE TITLE
Consider power consumption warning

### ISSUE THREAD

**Issue by brs17** [elementary/installer#251]
Currently if a machine is running off of battery power, a screen will appear recommending the user plug in to a power source.

_Something to consider_:
What if a user begins plugged in and then unplugs their machine after where the `Connect to a power source` screen appears.

Possible things to consider:

- A suggestion to plug in the machine towards the beginning of the installation
- Show the `Connect to a power source` screen at anytime before the actual installation begins

@cassidyjames thoughts?

**Comment by cassidyjames** [comment]
Yeah the theoretical situation we were talking about in person is:

User's laptop battery is low, but their laptop is currently plugged in. They step through the first few screens, then when the progress bar starts, they unplug their laptop (i.e. to carry it across the room while doing something else, to keep their eye on the installation). Their laptop battery dies and their install is wrecked.

We also don't show any battery status (at least in elementary OS, because we don't have a panel in the installer environment), so there's not a good way for a user to know their battery status.
