### ISSUE TITLE
Simple InstallType view

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#328]
Something that would move us in the direction of #320 without much more work would be to start building the InstallType view where we can set up possible options, like the "Refresh," "Upgrade," etc. magic partitioning types. 

For now, it could simply support the "Clean Install" and "Custom…" types since those are already supported. Then when we do Home folder retention, it gives us a natural place to put it.

**Comment by cassidyjames** [comment]
Rough whiteboard sketches for posterity

![img_20180514_144157-01](https://user-images.githubusercontent.com/611168/40022719-06d6aa74-5786-11e8-8306-94dbef8d2331.jpeg)

**Comment by mmstick** [comment]
The autoinstall branch of distinst is pretty much ready to go for implementing this in the UI. It has the capability to [list possible installation options and types](https://github.com/pop-os/distinst/blob/autoinstall/src/auto/options.rs). Currently supports options for selecting from a list of possible refresh options, and optionally retaining home for each option.

The UI will need to decrypt LUKS devices ahead of time in order to detect installation options from LUKS devices, though.

**Comment by cassidyjames** [comment]
>The UI will need to decrypt LUKS devices ahead of time in order to detect installation options from LUKS devices, though.

Crap, I'll have to think that through. I'm currently working on pulling out an "InstallType" view that doesn't add any new functionality to give us something to start from.

**Comment by cassidyjames** [comment]
After prototyping a bit and discussing with @WatchMkr and @danrabbit, I am going to actually try combining the TryInstallView and InstallTypeView. Having both in a row felt awkward and artificially slow, so I think we can ask the question once and include Demo Mode as one of the options instead of having a whole dedicated screen for it.
