### ISSUE TITLE
After installation it's not maintaining the selected language

### ISSUE THREAD

**Issue by lsrzj** [elementary/installer#351]
When you install Elementary, you can choose the installer frontend language, so you choose, for example, brazilian portuguese. Then the OS is installed, but, when booted, all the OS screens are in english. It could do like Ubuntu does, if you choose another language for the installation frontend, the language is installed and configured for imediate use.

**Comment by ryonakano** [comment]
@lsrzj Which installer do you mean:

1. The new WIP installer which is at this repo
2. Current installer which is adopted in Loki
3. Current installer which is adopted in Juno Beta1
4. Something else?

**Comment by lsrzj** [comment]
I installed loki release that is downloaded as stable at elementary.io

**Comment by ryonakano** [comment]
@lsrzj OK, then I'm afraid I think you should close this issue because:

1. This repository is for the new WIP installer and not for the current installer for Loki & Juno (fork of Ubiquity)
2. This issue seems to be fixed on Juno Beta1, while it surely happens on Loki (I also confirmed this issue happen on Loki)

I'm not sure this issue also happens in this new installer. If it confirms that this issue also happens with it when it is finally released, then you (or anyone) can freely reopen this issue or create a new one.

Anyway, thank you for your report!!

**Comment by lsrzj** [comment]
Sorry about the confusion. As I saw the name "Installer" here, I thought is was about Elementary installation in general, not about a specific installer. So I'll close as you suggested. But where can I report this problem properly?

**Comment by ryonakano** [comment]
@lsrzj Hmm, this issue may be fixed for Juno Beta1. So first please test [Juno Beta1](https://developer.elementary.io/) and check whether this issue is fixed or not. If you found this issue is fixed, you don't have to report this issue. But if you are still reproducible this issue, I think you may want to report it at https://github.com/elementary/os-patches (I'm not sure here is appropriate but it contains forked ubiquity branch)
