### ISSUE TITLE
Switching to guest session is broken

### ISSUE THREAD

**Issue by codygarver** [elementary/installer#375]
Debugging this by abusing the bug Super+Window -> `sudo killall io.elementary.installer` -> `G_DEBUG_MESSAGES=all sudo io.elementary.installer` results:

```
(io.elementary.installer:2438): GLib-GIO-CRITICAL **: 10:53:16.246: g_dbus_connection_call_internal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
```

**Comment by danrabbit** [comment]
From rooting around in Ubiquity, it kind of seems like on the Ubuntu LiveCD, the installer session is actually a greeter

This probably makes sense because it would be shown first and logging out of the demo mode would just show the installer again instead of kicking you back to a useless lock/login screen

**Comment by danrabbit** [comment]
Actually this seems to be working in the latest daily
