### ISSUE TITLE
No option to install proprietary drivers

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/installer#418]
In the previous ubiquity installer, there was a checkbox to install proprietary drivers and codecs. In 5.1, this option would install the `bcmwl-kernel-source` package (for my Broadcom adapter) into the target system so that I had working WiFi when I booted into the installed system.

The new installer no longer has this option and have to dig out a USB ethernet adapter or remember the arcane commands to install the driver off the live media to get my WiFi working after install.

**Comment by davidmhewitt** [comment]
Opened a feature request against distinst as it would make sense for that to handle the backend side of this and then we'd need to provide a frontend checkbox or something for it:
https://github.com/pop-os/distinst/issues/228

**Comment by davidmhewitt** [comment]
Submitted a PR for distinst here: https://github.com/pop-os/distinst/pull/255

**Comment by davidmhewitt** [comment]
PR merged into distinst, steps for completing this now are:

- [ ] Import newest distinst snapshot into launchpad
- [ ] Decide where in the UI this option will go and what the copy will be
- [ ] Wire it up

**Comment by cassidyjames** [comment]
So in looking at the current design, I feel like the options are to:
- Add an entirely new view for this one thing (eww), or
- Add it to the Disk view.

I don't _love_ either, but I think it fits more on the disk view since it's presumably a single checkbox, and will only even apply to some users. 

In fact… @davidmhewitt do you know if we can detect ahead of time whether or not this will be needed? If so then I'd be more open to adding a view specifically for this if it will only appear on systems where it's needed rather than adding another potentially no-op step for everyone.

**Comment by cassidyjames** [comment]
Another consideration is how the flow will work for custom installations; if we're adding it to the disk view, we'll need to add it to the custom view as well. So I guess that's another point in favor of a dedicated step. :thinking:
