### ISSUE TITLE
Installation fails to boot on UEFI systems if disk encryption was enabled

### ISSUE THREAD

**Issue by marbetschar** [elementary/installer#457]
**Describe the bug**

I downloaded elementary OS Daily from 27th of Sept 2020 and did a bare metal installation on my Dell XPS 13. The installation went smooth without any issue with everything set to default - but after it completed and the machine did a restart, Odin fails to boot claiming it is not able to find a kernel (right after the Grub Boot Menu).

Then I re-installed without Disk Encryption and then Odin was able to boot.

**Expected behavior**

Being able to boot after a bare metal installation with enabled disk encryption :)

![Screenshot from 2020-09-28 08 22 47](https://user-images.githubusercontent.com/392542/94397296-d4e37a80-0163-11eb-8bc6-5d52b6107471.png)

**Comment by mick-wilson** [comment]
I experienced something similar, however I wasn't sure if it was this issue or https://github.com/elementary/installer/issues/438

In any case, I worked around it by 

* Going to the "advanced" disk configuration part of the wizard
* opening gparted and manually wiping the disk entirely
* Backing out of "advanced" and selecting "clean install" again. 

Once I had the disk wiped manually, even the encrypted "clean install" worked successfully.

**Comment by tyuio9** [comment]
I guess, it might be connected with Grub support for LUKS2 (Odin uses LUKS2). https://git.savannah.gnu.org/cgit/grub.git/commit/?id=365e0cc3e7e44151c14dd29514c2f870b49f9755

**Comment by meisenzahl** [comment]
I am not able to reproduce this issue with `elementaryos-6.0-daily.20201207`

@marbetschar can you confirm this?

**Comment by fabricio7p** [comment]
i'm also having trouble installing any build into my 2019 XPS 13 9300.
Install fails with
`ERROR: configuring chroot error: error installing packages`

Right after extracting files, i can see in the logs it tries to run chroot apt-get command and fails there.
Tried everything default, with internet.. No luck

**Comment by marbetschar** [comment]
@meisenzahl, as @fabricio7p said the current iso builds do have some installation issues. Will happily re-install on bare metal once the issues are resolved - cause I need a running machine to prepare for the exams ;)

**Comment by fabricio7p** [comment]
Just a note, my disk is not encrypted. Should i open another issue?
Do you have any ideas on why its failing on a chroot command?

**Comment by disaster123** [comment]
Same for me. Grub does not find the uuid after enabling encryption. Used image from 20210107

**Comment by davidmhewitt** [comment]
I've been doing some testing around this today and have the following information:

This **only** happens when installing with encryption on EFI systems, installing with encryption on a BIOS system works fine. A lot of VM software defaults to creating VMs without an EFI implementation and hence the installer boots in BIOS mode.

I've marked comments as off-topic where they were obviously talking about installation failures caused by other issues or weren't experiencing the issue because they were installing in BIOS mode as this is still very much an issue when installing any elementary OS 6.0 iso in UEFI mode with encryption enabled.

The reason why this works in BIOS mode is clear. The installer creates an unencrypted `/boot` mount that contains the kernel and initial ramdisk and GRUB is installed to the MBR. So, GRUB can easily find the kernel and initramfs on the unencrypted partition, boot those, and then the initramfs has support for unlocking the LUKS LVM and booting the system.

With a UEFI system, the installer creates or uses an unencrypted FAT32 `/boot/efi` mount that is the ESP, it *only* contains GRUB. The kernel and initramfs are in the `/boot` folder on the root filesystem which is *inside* the encrypted LVM. In theory, GRUB supports unlocking LUKS partitions, however as @tyuio9 says above, support for LUKS2 which distinst sets up has only recently been added to GRUB. It's unclear whether this support is in the version of GRUB we have because helpfully nobody does meaningful release numbers or changelogs. But it looks unlikely that it's supported.

I think we have a few routes of investigation, but there may be more I haven't thought of:

1) Get the installer to ensure there is a unencrypted `/boot` mount in addition to the ESP mounted at `/boot/efi`. This means that the kernels and initramfs files are installed to unencrypted storage and can easily be picked up by GRUB. We might want to look at reducing the size requirements for the ESP in this case, as we don't need a bunch of space for kernels on there. These size constraints might be hardcoded in distinst. Having the kernel and initramfs on unencrypted storage means malicious actors with physical access to the device could modify them, but this setup is not uncommon amongst linux distros. Fedora and Ubuntu use this setup of having the kernel and ramdisk on unencrypted storage. So from a privacy point of view, all data is secure. But if you're a super paranoid person that leaves your device unattended in places where there may be super advanced hackers, you might not feel as safe.

2) Switch the installer to use to LUKS1 instead of LUKS2. Not 100% sure whether this will work, but it gives GRUB a better chance of being able to decrypt the LUKS volumes. Decryption with GRUB is slower, isn't as pretty (as it's at the grub command line, instead of in the bootsplash) and potentially is more complicated with regards to keyboard layouts etc. But, it does solve the issue of the kernel and ramdisk being on unencrypted storage.

3) Look at something like `kernelstub` for managing copying kernels and ramdisks to the ESP automatically. This has the downsides of 1, but maybe results in a less complicated partition layout. I'm least sure about this option as I don't know what the integration between this and GRUB would be. Would need some more investigation if we thought something like this was a viable option.

My preferred option is 1 as it seems to be the most standard among other linux distros and seems to be the least invasive. I've already conducted a proof of concept that I can get this option to work, but it will need a bit more work to fix the size constraints and ensure it covers all the custom partitioning cases in the installer.

Thoughts?

**Comment by cassidyjames** [comment]
@davidmhewitt I guess my only question is, what is Pop!_OS doing with their image, as it doesn't seem to have this issue? Is it that they are using a different bootloader and don't support secure boot?

**Comment by davidmhewitt** [comment]
@cassidyjames I believe they're using systemd-boot instead of GRUB **and** kernelstub, not sure if they've got secure boot working with it, haven't tried a Pop!_OS image in a while. But yeah, there's special casing for doing these things for Pop! in distinst.

**Comment by pongloongyeat** [comment]
@cassidyjames Can confirm Pop!_OS is using `systemd-boot`. As for secure boot working, if by it _working_ you mean being able to boot with secure boot then no. Secure boot must be disabled prior to installing Pop!_OS (20.04)

**Comment by marbetschar** [comment]
@davidmhewitt just did a fresh bare metal install of `elementaryos-6.0-daily.20210201.iso` on my UEFI System (Dell XPS 7390) with all the default settings in the installer and enabled encryption. Worked like a charm!

**Comment by davidmhewitt** [comment]
@marbetschar Excellent news, thanks for confirming. I'm leaving this open for now as I believe it may still fail with encryption enabled if you do custom partitioning. But I'm glad to hear that the default case works!

**Comment by marbetschar** [comment]
@davidmhewitt I need to reinstall once again, cause I need dual boot with Windows. Any specifics you want me to test to ensure UEFI / encryption works properly?

**Comment by davidmhewitt** [comment]
I'm not actually sure whether it's even possible to set up encryption if you're doing custom partitioning. So I'd be interested to hear about whether that's true or not.

Secondly, I'd also be interested to hear whether you can install and boot with secure boot turned on.

**Comment by marbetschar** [comment]
@davidmhewitt I tested the mentioned scenarios on my Dell XPS 7390 using the `elementaryos-6.0-daily.20210201.iso` with the following results:

**Encryption with custom partitioning:**
Not Possible

**Preconditions for the Tests with enabled Secure Boot**

_I had elementary OS installed before with Secure Boot disabled. For the tests below the first thing I did is enabling it in my BIOS and then starting the elementary Installer. So I'm not 100% sure how Secure Boot behaves if it would have been enabled all the time (e.g. directly after the purchase of a Laptop)._

**1st attempt: Secure Boot enabled, default installation with enabled encryption:**

The first thing I tested. This worked without any issues and I was able to boot after the installation.

However, in the first boot attempt my machine ignored the newly installed system on my SSD and booted straight into the installer of the USB stick again. I had to unplug the stick and reboot once again. Then I was prompted with a blue screen which had a timeout of a few seconds and would then boot automatically - however I pressed a key, which lead me to the menu below (this way I was able to make a picture of it):

![4032-3024-max](https://user-images.githubusercontent.com/392542/107005619-3d84d880-6790-11eb-8f74-e4116ce3ef4a.jpg)

**2nd attempt: Secure Boot enabled, default installation w/o encryption:**

On the second attempt I once again made a default installation. But this time without encryption. This worked without any issues. The blue screen did not appear.

**3rd attempt: Secure Boot enabled, custom partitions**

In the third attempt I wanted to install with custom partitions. This was not possible, because I was not able to delete all of the partitions. One of the partitions had a "key" icon, so I guess this was locked due to the installation before and enabled Secure Boot (not sure though):

![4032-3024-max](https://user-images.githubusercontent.com/392542/107006033-d87db280-6790-11eb-94a8-5189df4a2197.jpg)

**4th attempt: Secure Boot enabled, default installation with enabled encryption**

So as a last step I went back and tried again installing like I did the first time: All defaults, with enabled encryption. This time I was not able to install at all. The Installer failed with the error message below:

![4032-3024-max](https://user-images.githubusercontent.com/392542/107006202-167ad680-6791-11eb-8b7a-2eb4ba5bda52.jpg)

**Comment by davidmhewitt** [comment]
@marbetschar 

I'm not sure what that first blue screen is, seems like part of the Dell firmware maybe.

As for the key symbol in GParted, that probably signifies the encrypted volume. Although I'm unsure why you'd be unable to delete it. It looks like you may have unlocked it as the installer window is able to see the partitions within. So maybe something was still blocking it from being deleted because it was unlocked.

It seems like the last failure might be something like https://github.com/elementary/installer/issues/438 although we've had a few reports recently that people have been unable to reproduce it.

**Comment by casasfernando** [comment]
I'm trying to achieve full disk encryption on my laptop (yes, this will include /boot, call me paranoid hahaha).
Unfortunately the default option leaves /boot unencrypted for the reasons mentioned above.

Would you consider to use luks1 for /boot partition (this can be decrypted by GRUB without any problems) and luks2 for the lvm container (where /, swap and other volumes reside)?

Also I can confirm that custom partitioning in the installer doesn't work for what I'm trying to achieve. Please find below the problems I found so far.

My scenario (/boot not part of LVM:

1. Boot Odin install media into try mode.
2. From Terminal I created the following partition layout:
    - Created 3 partitions for ESP, /boot and LVM
    - Used cryptsetup to format the partition for /boot using LUKS1
    - Used cryptsetup to format the partition for LVM using LUKS2
    - Opened LUKS2 partition with cryptsetup and created a LVM pv, vg (named ***elementaryos***) and 3 lvs (root, swap, home)
    - Closed LUKS2 partition
    - Closed Terminal
3. From the Applications menu I launched the installer
4. Selected custom installation
5. In the partitioning dialog I found the following problems:
    - The installer seems to expect that the encrypted volume is setup with LVM. In my case, the /boot partition is not a LVM container. The installer is able to decrypt it but then it doesn't allow me to select the decrypted volume to do anything. It can't be used at all. 
    - The "device" name used while decrypting the LUKS volume **must** match the vg name used in the LVM container (in my case I need to change the default value ***data*** to ***elementaryos***) otherwise it will not detect any lvs inside the vg and they will not be available for use.

Let me know if you have any questions or would like me to provide any other details.

Thanks.

**Comment by cassidyjames** [comment]
@davidmhewitt correct me if I'm wrong, but this was resolved with our OS updates during the beta cycle, yeah?

**Comment by davidmhewitt** [comment]
Yup, I think there are a bunch of issues confused into one in the comments here. But I'm in favour of closing this for more specific issues that people can raise as they encounter them. The standard, full-disk, encrypt everything but /boot works fine.
