### ISSUE TITLE
Option to install drivers 

### ISSUE THREAD

**Issue by btkostner** [elementary/installer#47]
Right now installing graphics drivers is a pain, especially due to configuration changes. It would be nice if the installer could detected the GPU and give an option to install proprietary drivers out of the box. Expanding on this, it would be nice if we could install other drivers like networking on install.

I realize this overlaps with AppCenter and the drivers section. But this would help a lot with the out of box experience.

**Comment by Conan-Kudo** [comment]
So... we do this in the Mageia installer (DrakX), and it causes untold problems because in many cases, installing the proprietary driver means that fallbacks have to be disabled. So you're basically trusting that the proprietary driver will *work*.

This is not only not true, it's not even true most of the time. Proprietary drivers tend to be brittle, and I would hazard to say this is something that should be handled *after* installation, for a couple of reasons:

1. Doing it during initial setup means that you can produce generic images to mass-deploy, which makes OEM cases much easier.

2. Doing it after initial installation means that at least there's valid, supportable baseline always, and if the experience is *still* subpar, they can switch to unsupported proprietary drivers.

**Comment by danrabbit** [comment]
Closing as "Won't Fix"
