### ISSUE TITLE
Hide terminal output when booting in to cryptsetup

### ISSUE THREAD

**Issue by hanaral** [elementary/installer#475]
Not sure if this is just with my machine, but there is a pretty ugly flash of text output in the top left corner before entering cryptsetup. I’m also unsure whether or not this behaviour can even be changed

**Comment by davidmhewitt** [comment]
Boot message output is already hidden, but if there is a message that the kernel considers critical enough that you need to see, it will forcibly show it.

There's currently a bug in the Ubuntu kernel that results in a "initramfs unpacking failed: Decoding failed" message appearing. The kernel considers this a critical error, but it's actually not a problem. I've seen that on all of my recent Odin machines, so I'm assuming that's probably the message you're seeing too.

Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1835660

It will be fixed in an Ubuntu kernel update.
