### ISSUE TITLE
Odin: Installer too big in VirtualBox (or VBox window too small)

### ISSUE THREAD

**Issue by marbetschar** [elementary/installer#491]
**Describe the bug**

Just wanted to install `elementaryos-6.0-daily.20210224.iso` in the freshly installed VirtualBox-6.1. For this I created a new VM and selected Ubuntu 64 Bit as operating system. When I start the box, the installer is not entirely visible - therefore its hard to install elementary:

![vbox-daily-installer](https://user-images.githubusercontent.com/392542/109121115-21e57000-7747-11eb-89a0-b1869aa455fa.png)

I'm aware that its possible to switch the graphics controller in the VM settings. However, when I select anything else than the default `VMSVGA`, VirtualBox claims its an `invalid setting` - and if I start the VM with the invalid setting, the installer is not shown completely  too:

![vbox-graphics-controller-invalid](https://user-images.githubusercontent.com/392542/109121285-59ecb300-7747-11eb-98a4-e9359497ceef.png)

**To Reproduce**

1. Go to https://www.virtualbox.org/
2. Download and install VirtualBox 6.1
3. Download elementary daily *.iso
4. Start VirtualBox
5. Create a new VM, selecting Ubuntu 64 Bit as operating system
6. Select the elementary daily iso to boot from in `VM Settings > Storage > Controller: IDE`
7. Start the VM and wait for the installer to appear

**Expected behavior**

Ideally the Installer is visible entirely, without any further actions needed by the user.

**Additional context**

I started VirtualBox on a elementary daily bare meta installation.

**Comment by davidmhewitt** [comment]
I know it doesn't solve the original issue, but starting the VM in EFI mode instead of legacy BIOS should give you a higher resolution.

I think it's something about the way the virtualbox GPU reports its resolutions because other virtualization software does not have this issue, even with legacy BIOS modes.

Either way, it feels like there needs to be a smaller minimum size for the installer, or a way to change resolution in the installer session, or both. As it's perfectly possible that this could happen on real hardware too if there's something wrong with the graphics driver etc

**Comment by geminis3** [comment]
Same issue with VMware Workstation

![image](https://user-images.githubusercontent.com/49411169/116802421-2d06a480-aad8-11eb-8be7-10fde50d8848.png)

**Comment by brunetton** [comment]
[This workaround](https://github.com/elementary/installer/issues/601#issuecomment-899809332) worked for me: drag the window with Super+Drag, in addition of activating EFI mode

**Comment by joeljose350** [comment]
This issue is also present in 6.1 Jolnir

**Comment by zizlog** [comment]
> This issue is also present in elementary OS 6.1 Jolnir.

Here is a workaround which worked for me: 
Hit the ESC key when Elementary starts counting down from 5 to 1 and edit the Kernel boot parameter: delete "quiet splash" and add "vga=ask" w/o the quotes. Not sure if "quiet splash" needs to be removed since there really isn't any splash screen anyway. vga=ask will get you a list of available resolutions. I went for 344.

This boot parameter will only last until the reboot once the installation is finished. I couldn't find a way to get into the boot parameters again on startup. Maybe ElementaryOS prevents it doing so. Anyway, I was able to tab & Enter all the way through to the login screen. 
![Screenshot 2022-01-09 at 21 31 54](https://user-images.githubusercontent.com/84068977/148701234-7935c5af-6998-455b-8f92-193f28469a6e.jpg)

![Screenshot 2022-01-09 at 21 33 18](https://user-images.githubusercontent.com/84068977/148701279-9d431c0e-2c43-4855-bf86-642739c4c5c0.jpg)

![Screenshot 2022-01-09 at 21 55 23](https://user-images.githubusercontent.com/84068977/148701282-d1019eb4-420f-451c-8a32-c6c773cf4f16.jpg)

**Comment by yarik303** [comment]
> 

well for me this just i set 1024x768 it turn back to 800x600

**Comment by spawnflagger** [comment]
FWIW, the installer (elementaryos-6.1-stable.20211218-rc.iso) had _no_ screen size issues under VMware Fusion (free Player license) 12.1.2 on macOS 10.15.7.  (I set the VM to EFI, didn't test on standard bios).

Also, the VM performance is acceptable even on my 2012 MacBookPro (w/SSD) - not sure why all the warnings about being on a VM...  And AppCenter even offers to install open-vm-tools-desktop, which is correct.  Auto-guest-resolution-resizing works, as does shared Clipboard.  (Share Folders too after adding line to /etc/fstab)
