### ISSUE TITLE
No option to set hostname

### ISSUE THREAD

**Issue by kdwk** [elementary/installer#512]
**Describe the bug**
Installer (Odin) does not let the user hostname. This can lead to very long and non-descriptive hostnames, since it uses the device's full name by default. The user has to edit the config files (like /etc/hostname) after installation to change the hostname, which is not a good experience.

**To Reproduce**
1. Go through the installer. You cannot change the hostname

**Expected behavior**
The installer should add an option to configure the hostname

**Screenshots**

**Desktop (please complete the following information):**
![Screenshot from 2021-05-01 07-12-40](https://user-images.githubusercontent.com/39268094/116775364-36e5c480-aa52-11eb-8d46-00a4f13f2bc5.png)

**Additional context**

**Comment by MrPotatoBobx** [comment]
i think this should be in the initial setup, not the installer, IMO, the installer only has one job, to get the OS on your drive, anything else can happen later

**Comment by gitSaptarshi** [comment]
![hostname placeholder](https://user-images.githubusercontent.com/37685073/124266230-541f3800-db54-11eb-8505-22965940e991.png)
This is a mockup I have came up with. I think it's relatively simple this way.

**Comment by cassidyjames** [comment]
The installer intentionally doesn't have a hostname step as it's an implementation detail for most users, and can be changed from the installed OS later if required for specific use cases. There are already open discussions (#383) and issues (https://github.com/elementary/switchboard-plug-sharing/issues/53) regarding how changing the hostname should work, but in summary: it shouldn't be in the System plug as that field will show the device model name from the OEM if it exists and so won't always show the hostname; instead, it should be handled in the Sharing plug because it affects things like network shares and the Bluetooth device name.

See: https://github.com/elementary/switchboard-plug-sharing/issues/53
