### ISSUE TITLE
ProgressView: Wallpaper takes several seconds to show behind logo

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#579]
At first I thought this was just an issue in VMs or slow storage, but it's reproducible for me across several fast machines with very fast storage as well.

On the ProgressView, the avatar widget starts with a solid background color; several seconds later, the default wallpaper finally loads in.

**Comment by danrabbit** [comment]
I've seen this too. It started when we switched from the deprecated method for setting the background image. I wonder if it makes sense to gresource a smaller version of the wallpaper for this. The FileIcon might be slower since it's loading the full size image instead of creating a smaller thumbnail from the file

**Comment by cassidyjames** [comment]
@danrabbit yeah that probably makes sense. It's convenient to be able to just point it at the default wallpaper so we don't have to maintain that in multiple places, but also it's an infrequent enough change that it's probably fine to just update the GResource for each release. :shrug:
