### ISSUE TITLE
Should not show "Password is a palindrome" if only one letter

### ISSUE THREAD

**Issue by NathanBnm** [elementary/installer#594]
I noticed that it shows "Password is a palindrome" when typing the first letter when choosing the user password. I assume it should not appear for this case.

**Comment by danrabbit** [comment]
Thanks for your issue report! We're using LibPasswordQuality for this feature which tracks its issues here: https://github.com/libpwquality/libpwquality . It would be much appreciated if you filed this issue upstream :)

Closing as "Out of scope" since this is an issue with libpwquality and not with code in the installer itself

**Comment by NathanBnm** [comment]
Thanks for the redirect :smile:. Opened https://github.com/libpwquality/libpwquality/issues/58.
