### ISSUE TITLE
(V8preview) Cancel and go back to new live session 

### ISSUE THREAD

**Issue by megatux** [elementary/installer#804]
### Problem

When running the installer I'd like to cancel it and continue with a new live session.(1)
I see the live session user login entry behind but it does not respond to interaction. It's odd to have it behind and not work. (2)

### Proposal

Option to cancel the installation and use the current login entry gui to continue to a new live session

**Comment by ryonakano** [comment]
> Option to cancel the installation and use the current login entry gui to continue to a new live session

You can select the live session (Demo Mode) after selecting your language and keyboard layout: 

![](https://raw.githubusercontent.com/elementary/installer/main/data/screenshot-try-install.png)

It is a bug that the "Live session user" login card is shown behind the installer window (reported at https://github.com/elementary/greeter/issues/732) and fixed in https://github.com/elementary/greeter/pull/754.
